# Generated by Django 4.1.10 on 2023-08-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchorid', models.IntegerField()),
                ('coorx', models.FloatField()),
                ('coory', models.FloatField()),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.exhibition')),
            ],
            options={
                'db_table': 'anchor',
            },
        ),
    ]
