USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON artlink.* TO 'root'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON bridge.* TO 'root'@'%' WITH GRANT OPTION;
CREATE DATABASE artlink;
CREATE DATABASE bridge;
FLUSH PRIVILEGES;
UPDATE user SET password=PASSWORD("$MYSQL_ROOT_PASSWORD") WHERE user='root';
