# Generated by Django 4.2.3 on 2023-07-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryid', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
    ]
