# Generated by Django 4.2.3 on 2023-07-31 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchorid', models.IntegerField()),
                ('coorx', models.FloatField()),
                ('coory', models.FloatField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
            ],
            options={
                'db_table': 'anchor',
            },
        ),
    ]
